[package]
name = "rusty-junctions-library-macro"
version = "0.1.0"
edition = "2021"

[dependencies]
rusty-junctions-utils = { path = "rusty-junctions-utils" }
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full"] }
quote = "1.0"

[lib]
proc-macro = true